# Generated by Django 5.1.1 on 2024-10-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('user_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'unique_together': {('user_code',)},
            },
        ),
    ]
